GET http://localhost:3000/todos

###

POST http://localhost:3000/todos/new
Content-Type: application/json

{
    "text" : "Order pizza"
}

###
DELETE http://localhost:3000/todos/delete/65e33bf27afc37ee016dbc3b


###
PUT http://localhost:3000/todos/complete/65e33bc27afc37ee016dbc38